POST http://localhost:5000/api/admin/destract-object HTTP/1.1
Content-Type: application/json

{
  "title": "Школа",
  "position": [
    50.43845573909214,
    30.522331213099548
  ],
  "postName": "01001",
  "address": "Вулиця Велика Васильківська",
  "type": "Соціальна інфраструктура",
  "area": "3000",
  "imgPath": "../",
  "text": "Зруйнована школа",
  "percentageOfDestruction": "Частково",
  "dateOfDestruction": "02.02.2022",
  "dateOfRecovery": "",
  "location": "Київ",
  "neighborhood": "Печерський"
}