POST http://localhost:5000/api/admin/destract-object HTTP/1.1
Content-Type: application/json

{
  "title": "Зруйнований будинок",
  "position": [
    50.47120974216647, 30.460232226633263
  ],
  "postName": "01001",
  "address": "Вулиця Берестейська",
  "type": "Соціальна інфраструктура",
  "area": "360",
  "imgPath": "../../public/img_14.png",
  "text": "Зруйнована школа",
  "percentageOfDestruction": "Частково",
  "dateOfDestruction": "02.02.2022",
  "dateOfRecovery": "",
  "location": "Київ",
  "neighborhood": "Печерський"
}